{% set version = "6.35.1" %}
package:
  name: heasoft
  version: {{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/lheasoft/lheasoft{{ version }}/heasoft-{{ version }}src.tar.gz
  sha256: 60515214c01dbf3bea13fce27b5a2335f0be051172c745922cfe4c0be442bbbb
  folder: heasoft

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - perl
    - pkg-config
  host:
    - astropy >=6.1.4
    - astropy-iers-data
    - cfitsio >=4.2.0
    - curl
    - libgcc-ng
    - libpng
    - libstdcxx-ng
    - matplotlib-base >=3.9.2
    - ncurses  # Provides libtinfo.so.6
    - numpy >=2.1.2
    - perl >=5.32.1,<6.0
    - python >=3.12
    - readline
    - scipy >=1.14.1
    - xorg-libx11
    - xorg-libxext
    - xorg-libxt
    - xorg-xproto
    - zlib
  run:
    - astropy >=6.1.4
    - astropy-iers-data
    - cfitsio >=4.2.0
    - {{ pin_compatible('curl') }}
    - {{ pin_compatible('libgcc-ng') }}
    - {{ pin_compatible('libpng') }}
    - {{ pin_compatible('libstdcxx-ng') }}
    - matplotlib-base >=3.9.2
    - {{ pin_compatible('ncurses') }}
    - {{ pin_compatible('numpy') }}
    - python >=3.12
    - {{ pin_compatible('readline') }}
    - scipy >=1.14.1
    - {{ pin_compatible('xorg-libx11') }}
    - {{ pin_compatible('xorg-libxext') }}
    - {{ pin_compatible('xorg-libxt') }}
    - {{ pin_compatible('xorg-xproto') }}
    - {{ pin_compatible('zlib') }}

test:
  commands:
    - test -f $PREFIX/bin/fhelp
    - bash -c "ls $PREFIX/x86_64-pc-linux-gnu*/headas-init.sh"

about:
  home: https://heasarc.gsfc.nasa.gov/lheasoft/
  license: Clear BSD License
  license_file: LICENSE
  summary: NASA High Energy Astrophysics Software (HEAsoft)
  description: |
    HEAsoft is a unified release of FTOOLS and XANADU software packages
    for high energy astrophysics data analysis, including tools like XSPEC.
  doc_url: https://heasarc.gsfc.nasa.gov/docs/software/heasoft/

extra:
  recipe-maintainers:
    - j34ni
