context:
  name: shs-libfabric
  version: 1.22.x

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/HewlettPackard/shs-libfabric/archive/v${{ version }}-ss.tar.gz
  sha256: 63c50e4803913d3d05b0ec085826bdee07c2415db01fee510b81986903872470

build:
  number: 0
  script: build.sh
  skip:
    - win
    - osx

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - libtool
    - make
    - pkg-config
  host:
    - libnl
    - libfuse ==2.9.9
    - shs-libcxi
  run:
    - libnl
    - shs-libcxi

tests:
  - script:
     - test -f $PREFIX/lib/libfabric.so 

about:
  homepage: https://github.com/HewlettPackard/shs-libfabric
  license: BSD-2-Clause OR GPL-2.0-only OR Linux-OpenIB OR MIT
  license_file:  # No standalone LICENSE file; SPDX identifiers in source files
  summary: 'CXI-enabled libfabric library'
  description: |
    Provides a CXI-enabled version of the libfabric library for high-performance networking.
    Licensed primarily under BSD-2-Clause OR GPL-2.0-only per source file SPDX identifiers.
    Some files (e.g., dmabuf_reg.h) use GPL-2.0 OR Linux-OpenIB, and one file (infiniband/ib_user_ioctl_verbs.h) uses (GPL-2.0 WITH Linux-syscall-note) OR Linux-OpenIB.
    One file (install-git-hook.sh) uses GPL-2.0. The file fasthash.h uses MIT License (no SPDX header).

extra:
  recipe-maintainers:
    - j34ni
